<ul class="title-top">

# Working papers

<hr style="border:1px solid blue">

</ul>

<ul class="paper-list">

<li class="paper-item">

<h3 class="paper-title">
What the press reveals about the unemployed: a lexicometric analysis of 12,996 articles published in the French written newspapers between 2005 and 2022
</h3>

<p class="paper-authors">
**Charly Marie**, David Bourguignon
</p>

<p class="publication-date">
Last version: February 2024
</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Having a job is a social norm in many countries, and violating this norm can be very badly perceived. We argue that unemployed people carry a stigma, defined as a mark that brings discredit and reduces a person to a despised characteristic. We use the Reinert unsupervised exploratory lexicometric method to analyze 12,996 articles published in the French written press from 2005 to 2021 to reveal the media images of the unemployed. First, the unemployed represent 0.027% of the articles published over the period studied, reflecting a very low visibility. Second, the main actor is largely absent from this media treatment, as the unemployed are mostly portrayed as a statistical and political issue rather than as people and experiences. Third, the unemployed present themselves as willing to work at almost any cost, but are sometimes portrayed as at least partly responsible for their situation. A better understanding of the image of the unemployed and its dissemination in the media allows for a better understanding of the stigma of unemployment.
:::

<p class="paper-pre-registration">
The R script will be published soon. Scraped data is proprietary and cannot be shared.
</p>

<p class="paper-congress">
This work was presented at the 21st congress of the European Association of Work and Organizational Psychology (EAWOP) in 2023; at the Multiple Poverty Congress of the School for Advanced Studies in the Social Work and Intervention.
</p>

<p class="paper-keywords">
Keywords: Unemployed; Framing; Media analysis
</p>

<a href="https://drive.google.com/file/d/1-CJutxvAAnSVe2OvIFDqxXuV0z7K7U0t/view?usp=sharing" class="download-link" target="_blank">Last draft in French, to be translated and augmented</a>

</li>

</ul>

------------------------------------------------------------------------

<ul class="paper-list">

<li class="paper-item">

<h3 class="paper-title">
French Validation of Pinel's Stigma Consciousness Questionnaire Among Unemployed People: Links with Well-Being, Motivation, objective Job Search Behavior, and Access to Employment
</h3>

<p class="paper-authors">
**Charly Marie**, Charlotte Rauscher, Morgane Hoffmann, David Bourguignon
</p>

<p class="publication-date">

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Previous studies have shown that unemployed people carry a highly negative stigma. We examined whether their anticipation of being stigmatized, measured as stigma consciousness, predicted core psychological processes, objective job search behavior, and access to employment both after three months. We first translated the Stigma Consciousness Questionnaire (Pinel, 1999), which was originally designed for women, gay and Black people, into French, and adapted it to a population of jobseekers. We then sent a survey to a large and representative sample of unemployed people (N = 30,000; nrespondents = 2,055). Responses were linked to administrative databases of the French Public Employment Service to assess if stigma consciousness predicted objective job search behavior and access to employment. The scale showed good psychometric properties. Controlling for important confounders, stigma consciousness negatively predicted well-being, reported health, and life satisfaction, and positively predicted social and identified-regulated motivation to (re)work. Three months post-survey, stigma consciousness predicted increased job search efforts among jobseekers who had been unemployed for at least one year. However, this more intensive job search did not result in increased reemployment after three or five months. Our results depict active long-term jobseekers trying to manage their stigma by pursuing an individual mobility strategy, which did not lead to regaining employment. This could potentially increase their stigma consciousness, further deteriorating their well-being, health, and life satisfaction, in turn negatively affecting their ability to work, suggesting a detrimental cycle where stigma consciousness is a crucial factor.
:::

<p class="paper-pre-registration">
Hypotheses and methods have been <a href="https://osf.io/wdxjb" target="_blank">preregistered</a>. The R script and the available data have been published at the <a href="https://osf.io/5g76f/" target="_blank">OSF repository</a>.
</p>

<p class="paper-keywords">
Keywords: Unemployment, Social stigma, Stigma consciousness, Health, Job search behavior
</p>

<a href="https://osf.io/preprints/psyarxiv/ac89v" class="download-link" target="_blank">Last draft</a>

</li>

------------------------------------------------------------------------

<ul class="title">

# Works in progress

<hr style="border:1px solid blue">

</ul>

<ul class="paper-list">

<li class="paper-item">

<h3 class="paper-title">
Barometer of the stigma of unemployment and the stigmatization of the unemployed
</h3>

<p class="paper-authors">
**Charly Marie**, Emma de Araujo, Morgane Hoffmann, David Bourguignon
</p>

<p class="publication-date">

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Previous studies have shown that unemployed people are negatively stereotyped and stigmatized, but few have taken their perspective, and no victimization survey has ever been conducted. We survey a large and representative sample of unemployed people in France to investigate their experiences of stigma on a daily or acute basis; their anticipation of being the target of stereotypes, prejudice and discrimination; and their internalization of the stigma of unemployment. The responses, which are still being analyzed, mostly report high levels of acute and daily experiences of stigma; high levels of stigma consciousness and moderate levels of anticipation of stigmatization; and moderate to low levels of internalization of the stigma of unemployment.
:::

<p class="paper-pre-registration">
This is a re analysis of data collected with Emma de Araujo for the work *A focus on the interplay of socio-emotional skills, beliefs and stigma to predict job-search behaviors among the unemployed*. Available data can be found at the same <a href="https://osf.io/a6dm7/" target="_blank">OSF repository</a>. The first study was approved by the Institutional Review Board of the Paris Cité University under the reference 00012023-140.
</p>

<p class="paper-keywords">
Keywords: Stigma, Unemployment, Panel, Barometer
</p>

<a>Draft not yet available</a>

</li>

------------------------------------------------------------------------

<li class="paper-item">

<h3 class="paper-title">
An Adaptive Experiment to Boost Online Skill Signaling and Visibility
</h3>

<p class="paper-authors">
Morgane Hoffmann, Bertille Picard, **Charly Marie**, Guillaume Bied
</p>

<p class="publication-date">
Last version: November 2023
</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Digital matching platforms promise to reduce frictions on the labor market by providing low-cost information on available positions and candidates. As such, they may form a welcome addition to the toolbox available to Public Employment Services to bridge labor supply and demand. However, there are certain challenges associated with their adoption. For instance, vulnerable populations may face difficulties in utilizing digital tools effectively. In this study, we evaluate the impact of a communication campaign by email designed to encourage the use of an online matching platform maintained by the French Public Employment Service, Pôle emploi. We designed several email templates that combined information, support, or motivational content to encourage jobseekers to engage with their profiles on the platform. In order to discover email effectiveness, we implement an adaptive experiment (contextual bandit) where the goal is to use past jobseekers' take-up responses and characteristics to determine email allocation in the future, reducing gradually the allocation of less promising templates. Additionally, we built an optimal personalization allocation strategy based on collected data and test its effectiveness. Emails had a positive impact on the usage of the platform, as measured by a wide range of outcomes. However, attempts at learning a personalized emailing strategy did not manage to significantly improve on a random allocation of email templates.
:::

<p class="paper-pre-registration">
The pre-registration can be found at the <a href="https://www.socialscienceregistry.org/trials/10085" target="_blank">American Economic Association's registry for randomized controlled trials</a>. The study was approved by the Institutional Review Board of the Paris School of Economics under the reference 2022 - 019.
</p>

<p class="paper-congress">
This work was presented at the Machine Learning in Program Evaluation, High-Dimensionality and Visualization Techniques conference of the Luxembourg Institute of Socio-Economic Research (LISER) in 2023; at the 13th International Conference of the French Association of Experimental Economics (ASFEE), Montpellier, in 2023; at the 62nd Congress of the French Psychological Society, in 2023.
</p>

<p class="paper-keywords">
Keywords: Online Job Platforms, Contextual bandits, Behavioral science
</p>

<a href="https://bertillepicard.github.io/documents/papers/AnAdaptiveExpeToBoostOnlineSkillsSignaling.pdf" class="download-link" target="_blank">Last draft</a>

</li>

------------------------------------------------------------------------

<li class="paper-item">

<h3 class="paper-title">
From Hidden Skills to Opportunities : The Impact of Job Portals use on Labor Market Outcomes</h3>

<p class="paper-authors">
Morgane Hoffmann, Bertille Picard, Guillaume Bied, **Charly Marie**
</p>

<p class="publication-date">

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Temporary abstract: In this paper, we propose to investigate the benefits of the use of digital matching platform. In partnership with the French Public Employment Service, France travail, we encourage randomly selected registered jobseekers to fill-in and publish their profile on the PES platform to make them more visible to recruiters. We then track the effects of the intervention on a large variety of outcomes, including employment, using rich administrative data and web logs provided by the French Employment Service.
:::

<p class="paper-pre-registration">
The pre-registration can be found at the <a href="https://www.socialscienceregistry.org/trials/10085" target="_blank">American Economic Association's registry for randomized controlled trials</a> and the study was approved by the Paris School of Economics' Institutional Review Board under the reference 2022 - 019.
</p>

<p class="paper-keywords">
Keywords:
</p>

<a>Draft not yet available</a>

</li>

------------------------------------------------------------------------

<li class="paper-item">

<h3 class="paper-title">
French translation and validation of the Job search self-efficacy scale (Saks & al., 2015)
</h3>

<p class="paper-authors">
Charlotte Rauscher, **Charly Marie**, Morgane Hoffmann
</p>

<p class="publication-date">

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Coming soon :)
:::

<p class="paper-pre-registration">
Hypotheses and methods have been <a href="https://osf.io/hnbuk" target="_blank">preregistered</a>. The R script and the available data will be published at the <a href="https://osf.io/5g76f/" target="_blank">OSF repository</a>.
</p>

<p class="paper-keywords">
Keywords: Job search, Self-efficacy, Unemployment
</p>

<a>Draft not yet available</a>

</li>

------------------------------------------------------------------------

<li class="paper-item">

<h3 class="paper-title">
A focus on the interplay of socio-emotional skills, beliefs and stigma to predict job-search behaviors among the unemployed
</h3>

<p class="paper-authors">
Emma de Araujo, **Charly Marie** (both first authors), Morgane Hoffmann, David Bourguignon, Grégoire Borst
</p>

<p class="publication-date">

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Temporary abstract: Research has identified psychological predictors of job search behavior, but much of it has been conducted in separate streams of research and often studied in isolation from one another. As a result, it is unclear which psychological factors are relatively more influential in the job search process. We conceptualize job search as a goal-directed, self-regulatory process that involves core psychological processes to initiate and maintain job search behavior. We draw on cognitive and social-cognitive psychology to integrate three complementary levels of analysis related to self-regulatory mechanisms: the personal-cognitive level, with social-emotional and cognitive skills; the personal-self level, with beliefs about one's own skills and abilities; the interpersonal and intergroup level, with stigmatization. The results will allow (1) to map the relative importance of key self-regulatory mechanisms at complementary levels of analysis; and (2) to test psychological notions that have never been evaluated and that may play a role in the job search process.
:::

<p class="paper-pre-registration">
Hypotheses and methods have been <a href="https://osf.io/uf8ce" target="_blank">preregistered</a>. The R script and the available data will be published at the <a href="https://osf.io/a6dm7/" target="_blank">OSF repository</a>. The study was approved by the Institutional Review Board of the Paris Cité University under the reference 00012023-140.
</p>

<p class="paper-keywords">
Keywords: Job search, Self-control, Fluid intelligence, Self-efficacy, Mindsets, Locus of control, Anticipated stigma, Experienced stigma, Internalized stigma
</p>

<a>Draft not yet available</a>

</li>

------------------------------------------------------------------------

<li class="paper-item">

<h3 class="paper-title">
"You're a nobody when you're unemployed": Unemployed's label, through a social cognition perspective
</h3>

<p class="paper-authors">
**Charly Marie**, Pierre Bouchat, David Bourguignon
</p>

<p class="publication-date">

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Coming soon :)
:::

<p class="paper-pre-registration">
The R script and data will be published soon.
</p>

<p class="paper-congress">
This work was presented at the 21st congress of the European Association of Work and Organizational Psychology (EAWOP) in 2023; and as a poster at the 19th General Meeting of the European Association of Social Psychology (EASP) in 2023.
</p>

<p class="paper-keywords">
Keywords:
</p>

<a>Draft not yet available</a>

</li>

</ul>

------------------------------------------------------------------------

<ul class="title">

# Book chapter

<hr style="border:1px solid blue">

</ul>

<ul class="paper-list">

<li class="paper-item">

<h3 class="paper-title">
Le chômage et la stigmatisation à l'oeuvre \[Unemployment and stigma in action\]
</h3>

<h3 class="book-title">
*in* Psychologie de la discrimination et des préjugés: De la théorie à la pratique \[Psychology of discrimination and prejudice: From theory to practice\]
</h3>

<p class="paper-authors">
David Bourguignon, Selma Seghouat, **Charly Marie**, Ginette Herman
</p>

<p class="publication-date">

2022

</p>

::: {.callout-note collapse="true" icon=false appearance="default"}
## Abstract
Les effets délétères de la privation d'emploi sur la santé mentale sont largement étayés dans la littérature scientifique. En psychologie, la plupart des travaux ont expliqué ces effets au travers d'une perspective individuelle, laissant dans l'ombre la dimension intergroupe. Pourtant, de la situation de chômage émergent deux groupes, celui des travailleur⸱euses et celui des chômeur⸱euses. Alors que le premier est en adéquation avec une norme sociale valorisée « celle de travailler », le second, par déviance à cette norme, est la cible de préjugés véhiculés par la société. Confronté à la dévalorisation, le groupe des chômeurs et des chômeuses développe une identité sociale négative nuisant à la santé mentale et l'insertion sociale et professionnelle. Cette configuration est la voie principale conduisant au processus de stigmatisation. Quelles sont les stratégies de défense de soi que les chômeur·euses mettent en oeuvre pour le contrer ? Les travaux que nous avons réalisés montrent que, contrairement à de nombreux groupes qui parviennent à protéger leur santé mentale en s'identifiant davantage à leur groupe d'appartenance (par ex., les femmes), les personnes sans emploi ne bénéficient pas des effets positifs d'une telle stratégie, que du contraire. Toutefois, lorsque les chômeur⸱euses contestent le bien-fondé de la dévalorisation qui s'exerce à l'égard de leur groupe, leur identité acquiert une valeur protectrice. Nous développerons cette dimension dans le chapitre, qui se conclut par une réflexion sur les liens entre la stigmatisation, les stratégies de défense de soi et les questions d'intégration au sein du marché de l'emploi.
:::

<p class="paper-keywords">
Keywords: Chômage, Stigmatisation, Coping
</p>

<a>Proprietary chapter, which cannot be shared.</a>

</li>

------------------------------------------------------------------------