As a researcher and practitioner on both subjects of the social assignment of the unemployed, and the use of psychological theories and methods to the construction and development of public policies, I have been invited to speak to various institutions and associations.

<br>

<ul class="title-top">

# As a researcher

</ul>

<div>

-   The annual meeting of the [Sève emploi network](https://www.federationsolidarite.org/innovations-et-services/innovations/seve-emploi/){target="_blank"} Grand-Est (2022) and Normandy (2023). I talked about the stereotypes of the unemployed, their drivers and consequences from the point of view of case workers, the unemployed and HR managers, as well as ways to mitigate their effects for the job market, the people and the companies.

</div>

<ul class="title">

# As a practitioner

</ul>

<div>

-   We were invited to present the work that has been initiated in the French PES in the field of behavioral insights at the Network of European Public Employment Services (the [*PES Network*](https://ec.europa.eu/social/main.jsp?catId=1100&langId=en){target="_blank"}). Participants included behavioral science experts from the German, Dutch, Icelandic, Swedish, and many other EU PES.

</div>

</ul>
