<ul class="title-top">

# What is behavioral science

</ul>

Behavioral science is a transdisciplinary lens that seeks to explain and predict the environmental causes and psychological processes that underlie the decisions, emotions, and behaviors of individuals, groups, and organizations.

I have long been a strong advocate of this approach, which brings together psychology and public policy, and was fortunate enough to become the **behavioral science and insights expert for the French Public Employment Service** (PES) while working on my doctoral dissertation.

<ul class="title">

# What I had the opportunity to do

</ul>

There, I had the opportunity to work with some of the most competent and caring experts in the field, who have taught me a great deal. Overall, we have:

<div>

1.  **Tested several ways to apply behavioral science to a variety of contexts**, including employment of people with disabilities, the online application form, hands-on work experience that allows an unemployed person to experience a work situation, or the relationship between a caseworker and a job seeker.

2.  **Incorporated basic psychological concepts into the initial and ongoing vocational training of caseworkers**, such as (job search) self-efficacy, the different forms of (re)work motivation, the importance of the social norm, etc., which then had a positive influence on the relationship between a caseworker and a client.

3.  **Demonstrated the relevance of the behavioral science approach**, which has become part of the global range of expertise used by PES to construct and develop public employment policies.

</div>

I also had the opportunity to present our work to the Network of European Public Employment Services (the [*PES Network*](https://ec.europa.eu/social/main.jsp?catId=1100&langId=en){target="_blank"}) and to help prepare a meeting of the [*G20 Behavioral Insights Knowledge Exchange Network*](http://www.g20.utoronto.ca/2020/G20SS_Labour_And_Employment_Ministerial_Declaration_EN.pdf){target="_blank"} for the French authorities.

<ul class="title">

# What I would like to keep doing

</ul>

As of today, my overall goal is to further develop my skills and abilities in the application of psychology to both the construction and development of public policy. See the Research page for some of the work we have done to this end.
